// @ts-check
/** @type {import('@stryker-mutator/api/core').StrykerOptions} */
export default {
  _comment:
    "This config was generated by 'stryker init'. Please take a look at: https://stryker-mutator.io/docs/stryker-js/configuration/ for more information.",
  packageManager: "pnpm",
  reporters: ["html", "clear-text", "progress"],
  testRunner: "vitest",
  coverageAnalysis: "perTest",
  checkers: [],
  plugins: ["@stryker-mutator/vitest-runner"],
  tsconfigFile: "tsconfig.json",
  vitest: {
    configFile: "vitest.config.ts",
  },
  mutate: [
    "src/**/*.ts",
    "!src/**/*.test.ts",
    "!src/app/**/*.ts",
    "!src/components/**/*.ts",
    "!src/core/db/**/*.ts",
    "!src/core/enums/**/*.ts",
    "!src/core/errors/**/*.ts",
    "!src/core/features/onboarding/ports/**/*.ts",
    "!src/core/features/onboarding/schemas/**/*.ts",
    "!src/core/services/clerk-service-tag.ts",
    "!src/core/services/drizzle-service-tag.ts",
    "!src/hooks/**/*.ts",
    "!src/lib/**/*.ts",
    "!src/types/**/*.ts",
    "!src/middleware.ts",
  ],
};