// @ts-check
/** @type {import('@stryker-mutator/api/core').StrykerOptions} */
export default {
  _comment:
    "This config was generated by 'stryker init'. Please take a look at: https://stryker-mutator.io/docs/stryker-js/configuration/ for more information.",
  packageManager: "pnpm",
  reporters: ["html", "clear-text", "progress"],
  testRunner: "vitest",
  coverageAnalysis: "perTest",
  checkers: [],
  plugins: ["@stryker-mutator/vitest-runner"],
  tsconfigFile: "tsconfig.json",
  vitest: {
    configFile: "vitest.config.ts",
  },
  mutate: [
    "src/core/**/*.ts",
    "!src/**/*.test.ts",
    "!src/**/*.tag.ts",
    "!src/core/db/**/*.ts",
    "!src/core/enums/**/*.ts",
    "!src/core/errors/**/*.ts",
  ],
};
