export enum Country {
  AF = "AF",
  AL = "AL",
  DZ = "DZ",
  AS = "AS",
  AD = "AD",
  AO = "AO",
  AI = "AI",
  AQ = "AQ",
  AG = "AG",
  AR = "AR",
  AM = "AM",
  AW = "AW",
  AU = "AU",
  AT = "AT",
  AZ = "AZ",
  BS = "BS",
  BH = "BH",
  BD = "BD",
  BB = "BB",
  BY = "BY",
  BE = "BE",
  BZ = "BZ",
  BJ = "BJ",
  BM = "BM",
  BT = "BT",
  BO = "BO",
  BQ = "BQ",
  BA = "BA",
  BW = "BW",
  BV = "BV",
  BR = "BR",
  IO = "IO",
  BN = "BN",
  BG = "BG",
  BF = "BF",
  BI = "BI",
  CV = "CV",
  KH = "KH",
  CM = "CM",
  CA = "CA",
  KY = "KY",
  CF = "CF",
  TD = "TD",
  CL = "CL",
  CN = "CN",
  CX = "CX",
  CC = "CC",
  CO = "CO",
  KM = "KM",
  CD = "CD",
  CG = "CG",
  CK = "CK",
  CR = "CR",
  HR = "HR",
  CU = "CU",
  CW = "CW",
  CY = "CY",
  CZ = "CZ",
  CI = "CI",
  DK = "DK",
  DJ = "DJ",
  DM = "DM",
  DO = "DO",
  EC = "EC",
  EG = "EG",
  SV = "SV",
  GQ = "GQ",
  ER = "ER",
  EE = "EE",
  SZ = "SZ",
  ET = "ET",
  FK = "FK",
  FO = "FO",
  FJ = "FJ",
  FI = "FI",
  FR = "FR",
  GF = "GF",
  PF = "PF",
  TF = "TF",
  GA = "GA",
  GM = "GM",
  GE = "GE",
  DE = "DE",
  GH = "GH",
  GI = "GI",
  GR = "GR",
  GL = "GL",
  GD = "GD",
  GP = "GP",
  GU = "GU",
  GT = "GT",
  GG = "GG",
  GN = "GN",
  GW = "GW",
  GY = "GY",
  HT = "HT",
  HM = "HM",
  VA = "VA",
  HN = "HN",
  HK = "HK",
  HU = "HU",
  IS = "IS",
  IN = "IN",
  ID = "ID",
  IR = "IR",
  IQ = "IQ",
  IE = "IE",
  IM = "IM",
  IL = "IL",
  IT = "IT",
  JM = "JM",
  JP = "JP",
  JE = "JE",
  JO = "JO",
  KZ = "KZ",
  KE = "KE",
  KI = "KI",
  KP = "KP",
  KR = "KR",
  KW = "KW",
  KG = "KG",
  LA = "LA",
  LV = "LV",
  LB = "LB",
  LS = "LS",
  LR = "LR",
  LY = "LY",
  LI = "LI",
  LT = "LT",
  LU = "LU",
  MO = "MO",
  MG = "MG",
  MW = "MW",
  MY = "MY",
  MV = "MV",
  ML = "ML",
  MT = "MT",
  MH = "MH",
  MQ = "MQ",
  MR = "MR",
  MU = "MU",
  YT = "YT",
  MX = "MX",
  FM = "FM",
  MD = "MD",
  MC = "MC",
  MN = "MN",
  ME = "ME",
  MS = "MS",
  MA = "MA",
  MZ = "MZ",
  MM = "MM",
  NA = "NA",
  NR = "NR",
  NP = "NP",
  NL = "NL",
  NC = "NC",
  NZ = "NZ",
  NI = "NI",
  NE = "NE",
  NG = "NG",
  NU = "NU",
  NF = "NF",
  MP = "MP",
  NO = "NO",
  OM = "OM",
  PK = "PK",
  PW = "PW",
  PS = "PS",
  PA = "PA",
  PG = "PG",
  PY = "PY",
  PE = "PE",
  PH = "PH",
  PN = "PN",
  PL = "PL",
  PT = "PT",
  PR = "PR",
  QA = "QA",
  MK = "MK",
  RO = "RO",
  RU = "RU",
  RW = "RW",
  RE = "RE",
  BL = "BL",
  SH = "SH",
  KN = "KN",
  LC = "LC",
  MF = "MF",
  PM = "PM",
  VC = "VC",
  WS = "WS",
  SM = "SM",
  ST = "ST",
  SA = "SA",
  SN = "SN",
  RS = "RS",
  SC = "SC",
  SL = "SL",
  SG = "SG",
  SX = "SX",
  SK = "SK",
  SI = "SI",
  SB = "SB",
  SO = "SO",
  ZA = "ZA",
  GS = "GS",
  SS = "SS",
  ES = "ES",
  LK = "LK",
  SD = "SD",
  SR = "SR",
  SJ = "SJ",
  SE = "SE",
  CH = "CH",
  SY = "SY",
  TW = "TW",
  TJ = "TJ",
  TZ = "TZ",
  TH = "TH",
  TL = "TL",
  TG = "TG",
  TK = "TK",
  TO = "TO",
  TT = "TT",
  TN = "TN",
  TR = "TR",
  TM = "TM",
  TC = "TC",
  TV = "TV",
  UG = "UG",
  UA = "UA",
  AE = "AE",
  GB = "GB",
  UM = "UM",
  US = "US",
  UY = "UY",
  UZ = "UZ",
  VU = "VU",
  VE = "VE",
  VN = "VN",
  VG = "VG",
  VI = "VI",
  WF = "WF",
  EH = "EH",
  YE = "YE",
  ZM = "ZM",
  ZW = "ZW",
  AX = "AX",
}

export const COUNTRIES = [
  { name: "Afghanistan", alpha_2_code: Country.AF },
  { name: "Albania", alpha_2_code: Country.AL },
  { name: "Algeria", alpha_2_code: Country.DZ },
  { name: "American Samoa", alpha_2_code: Country.AS },
  { name: "Andorra", alpha_2_code: Country.AD },
  { name: "Angola", alpha_2_code: Country.AO },
  { name: "Anguilla", alpha_2_code: Country.AI },
  { name: "Antarctica", alpha_2_code: Country.AQ },
  { name: "Antigua and Barbuda", alpha_2_code: Country.AG },
  { name: "Argentina", alpha_2_code: Country.AR },
  { name: "Armenia", alpha_2_code: Country.AM },
  { name: "Aruba", alpha_2_code: Country.AW },
  { name: "Australia", alpha_2_code: Country.AU },
  { name: "Austria", alpha_2_code: Country.AT },
  { name: "Azerbaijan", alpha_2_code: Country.AZ },
  { name: "Bahamas (the)", alpha_2_code: Country.BS },
  { name: "Bahrain", alpha_2_code: Country.BH },
  { name: "Bangladesh", alpha_2_code: Country.BD },
  { name: "Barbados", alpha_2_code: Country.BB },
  { name: "Belarus", alpha_2_code: Country.BY },
  { name: "Belgium", alpha_2_code: Country.BE },
  { name: "Belize", alpha_2_code: Country.BZ },
  { name: "Benin", alpha_2_code: Country.BJ },
  { name: "Bermuda", alpha_2_code: Country.BM },
  { name: "Bhutan", alpha_2_code: Country.BT },
  { name: "Bolivia (Plurinational State of)", alpha_2_code: Country.BO },
  { name: "Bonaire, Sint Eustatius and Saba", alpha_2_code: Country.BQ },
  { name: "Bosnia and Herzegovina", alpha_2_code: Country.BA },
  { name: "Botswana", alpha_2_code: Country.BW },
  { name: "Bouvet Island", alpha_2_code: Country.BV },
  { name: "Brazil", alpha_2_code: Country.BR },
  { name: "British Indian Ocean Territory (the)", alpha_2_code: Country.IO },
  { name: "Brunei Darussalam", alpha_2_code: Country.BN },
  { name: "Bulgaria", alpha_2_code: Country.BG },
  { name: "Burkina Faso", alpha_2_code: Country.BF },
  { name: "Burundi", alpha_2_code: Country.BI },
  { name: "Cabo Verde", alpha_2_code: Country.CV },
  { name: "Cambodia", alpha_2_code: Country.KH },
  { name: "Cameroon", alpha_2_code: Country.CM },
  { name: "Canada", alpha_2_code: Country.CA },
  { name: "Cayman Islands (the)", alpha_2_code: Country.KY },
  { name: "Central African Republic (the)", alpha_2_code: Country.CF },
  { name: "Chad", alpha_2_code: Country.TD },
  { name: "Chile", alpha_2_code: Country.CL },
  { name: "China", alpha_2_code: Country.CN },
  { name: "Christmas Island", alpha_2_code: Country.CX },
  { name: "Cocos (Keeling) Islands (the)", alpha_2_code: Country.CC },
  { name: "Colombia", alpha_2_code: Country.CO },
  { name: "Comoros (the)", alpha_2_code: Country.KM },
  { name: "Congo (the Democratic Republic of the)", alpha_2_code: Country.CD },
  { name: "Congo (the)", alpha_2_code: Country.CG },
  { name: "Cook Islands (the)", alpha_2_code: Country.CK },
  { name: "Costa Rica", alpha_2_code: Country.CR },
  { name: "Croatia", alpha_2_code: Country.HR },
  { name: "Cuba", alpha_2_code: Country.CU },
  { name: "Curaçao", alpha_2_code: Country.CW },
  { name: "Cyprus", alpha_2_code: Country.CY },
  { name: "Czechia", alpha_2_code: Country.CZ },
  { name: "Côte d'Ivoire", alpha_2_code: Country.CI },
  { name: "Denmark", alpha_2_code: Country.DK },
  { name: "Djibouti", alpha_2_code: Country.DJ },
  { name: "Dominica", alpha_2_code: Country.DM },
  { name: "Dominican Republic (the)", alpha_2_code: Country.DO },
  { name: "Ecuador", alpha_2_code: Country.EC },
  { name: "Egypt", alpha_2_code: Country.EG },
  { name: "El Salvador", alpha_2_code: Country.SV },
  { name: "Equatorial Guinea", alpha_2_code: Country.GQ },
  { name: "Eritrea", alpha_2_code: Country.ER },
  { name: "Estonia", alpha_2_code: Country.EE },
  { name: "Eswatini", alpha_2_code: Country.SZ },
  { name: "Ethiopia", alpha_2_code: Country.ET },
  { name: "Falkland Islands (the) [Malvinas]", alpha_2_code: Country.FK },
  { name: "Faroe Islands (the)", alpha_2_code: Country.FO },
  { name: "Fiji", alpha_2_code: Country.FJ },
  { name: "Finland", alpha_2_code: Country.FI },
  { name: "France", alpha_2_code: Country.FR },
  { name: "French Guiana", alpha_2_code: Country.GF },
  { name: "French Polynesia", alpha_2_code: Country.PF },
  { name: "French Southern Territories (the)", alpha_2_code: Country.TF },
  { name: "Gabon", alpha_2_code: Country.GA },
  { name: "Gambia (the)", alpha_2_code: Country.GM },
  { name: "Georgia", alpha_2_code: Country.GE },
  { name: "Germany", alpha_2_code: Country.DE },
  { name: "Ghana", alpha_2_code: Country.GH },
  { name: "Gibraltar", alpha_2_code: Country.GI },
  { name: "Greece", alpha_2_code: Country.GR },
  { name: "Greenland", alpha_2_code: Country.GL },
  { name: "Grenada", alpha_2_code: Country.GD },
  { name: "Guadeloupe", alpha_2_code: Country.GP },
  { name: "Guam", alpha_2_code: Country.GU },
  { name: "Guatemala", alpha_2_code: Country.GT },
  { name: "Guernsey", alpha_2_code: Country.GG },
  { name: "Guinea", alpha_2_code: Country.GN },
  { name: "Guinea-Bissau", alpha_2_code: Country.GW },
  { name: "Guyana", alpha_2_code: Country.GY },
  { name: "Haiti", alpha_2_code: Country.HT },
  { name: "Heard Island and McDonald Islands", alpha_2_code: Country.HM },
  { name: "Holy See (the)", alpha_2_code: Country.VA },
  { name: "Honduras", alpha_2_code: Country.HN },
  { name: "Hong Kong", alpha_2_code: Country.HK },
  { name: "Hungary", alpha_2_code: Country.HU },
  { name: "Iceland", alpha_2_code: Country.IS },
  { name: "India", alpha_2_code: Country.IN },
  { name: "Indonesia", alpha_2_code: Country.ID },
  { name: "Iran (Islamic Republic of)", alpha_2_code: Country.IR },
  { name: "Iraq", alpha_2_code: Country.IQ },
  { name: "Ireland", alpha_2_code: Country.IE },
  { name: "Isle of Man", alpha_2_code: Country.IM },
  { name: "Israel", alpha_2_code: Country.IL },
  { name: "Italy", alpha_2_code: Country.IT },
  { name: "Jamaica", alpha_2_code: Country.JM },
  { name: "Japan", alpha_2_code: Country.JP },
  { name: "Jersey", alpha_2_code: Country.JE },
  { name: "Jordan", alpha_2_code: Country.JO },
  { name: "Kazakhstan", alpha_2_code: Country.KZ },
  { name: "Kenya", alpha_2_code: Country.KE },
  { name: "Kiribati", alpha_2_code: Country.KI },
  {
    name: "Korea (the Democratic People's Republic of)",
    alpha_2_code: Country.KP,
  },
  { name: "Korea (the Republic of)", alpha_2_code: Country.KR },
  { name: "Kuwait", alpha_2_code: Country.KW },
  { name: "Kyrgyzstan", alpha_2_code: Country.KG },
  { name: "Lao People's Democratic Republic (the)", alpha_2_code: Country.LA },
  { name: "Latvia", alpha_2_code: Country.LV },
  { name: "Lebanon", alpha_2_code: Country.LB },
  { name: "Lesotho", alpha_2_code: Country.LS },
  { name: "Liberia", alpha_2_code: Country.LR },
  { name: "Libya", alpha_2_code: Country.LY },
  { name: "Liechtenstein", alpha_2_code: Country.LI },
  { name: "Lithuania", alpha_2_code: Country.LT },
  { name: "Luxembourg", alpha_2_code: Country.LU },
  { name: "Macao", alpha_2_code: Country.MO },
  { name: "Madagascar", alpha_2_code: Country.MG },
  { name: "Malawi", alpha_2_code: Country.MW },
  { name: "Malaysia", alpha_2_code: Country.MY },
  { name: "Maldives", alpha_2_code: Country.MV },
  { name: "Mali", alpha_2_code: Country.ML },
  { name: "Malta", alpha_2_code: Country.MT },
  { name: "Marshall Islands (the)", alpha_2_code: Country.MH },
  { name: "Martinique", alpha_2_code: Country.MQ },
  { name: "Mauritania", alpha_2_code: Country.MR },
  { name: "Mauritius", alpha_2_code: Country.MU },
  { name: "Mayotte", alpha_2_code: Country.YT },
  { name: "Mexico", alpha_2_code: Country.MX },
  { name: "Micronesia (Federated States of)", alpha_2_code: Country.FM },
  { name: "Moldova (the Republic of)", alpha_2_code: Country.MD },
  { name: "Monaco", alpha_2_code: Country.MC },
  { name: "Mongolia", alpha_2_code: Country.MN },
  { name: "Montenegro", alpha_2_code: Country.ME },
  { name: "Montserrat", alpha_2_code: Country.MS },
  { name: "Morocco", alpha_2_code: Country.MA },
  { name: "Mozambique", alpha_2_code: Country.MZ },
  { name: "Myanmar", alpha_2_code: Country.MM },
  { name: "Namibia", alpha_2_code: Country.NA },
  { name: "Nauru", alpha_2_code: Country.NR },
  { name: "Nepal", alpha_2_code: Country.NP },
  { name: "Netherlands (the)", alpha_2_code: Country.NL },
  { name: "New Caledonia", alpha_2_code: Country.NC },
  { name: "New Zealand", alpha_2_code: Country.NZ },
  { name: "Nicaragua", alpha_2_code: Country.NI },
  { name: "Niger (the)", alpha_2_code: Country.NE },
  { name: "Nigeria", alpha_2_code: Country.NG },
  { name: "Niue", alpha_2_code: Country.NU },
  { name: "Norfolk Island", alpha_2_code: Country.NF },
  { name: "Northern Mariana Islands (the)", alpha_2_code: Country.MP },
  { name: "Norway", alpha_2_code: Country.NO },
  { name: "Oman", alpha_2_code: Country.OM },
  { name: "Pakistan", alpha_2_code: Country.PK },
  { name: "Palau", alpha_2_code: Country.PW },
  { name: "Palestine, State of", alpha_2_code: Country.PS },
  { name: "Panama", alpha_2_code: Country.PA },
  { name: "Papua New Guinea", alpha_2_code: Country.PG },
  { name: "Paraguay", alpha_2_code: Country.PY },
  { name: "Peru", alpha_2_code: Country.PE },
  { name: "Philippines (the)", alpha_2_code: Country.PH },
  { name: "Pitcairn", alpha_2_code: Country.PN },
  { name: "Poland", alpha_2_code: Country.PL },
  { name: "Portugal", alpha_2_code: Country.PT },
  { name: "Puerto Rico", alpha_2_code: Country.PR },
  { name: "Qatar", alpha_2_code: Country.QA },
  { name: "Republic of North Macedonia", alpha_2_code: Country.MK },
  { name: "Romania", alpha_2_code: Country.RO },
  { name: "Russian Federation (the)", alpha_2_code: Country.RU },
  { name: "Rwanda", alpha_2_code: Country.RW },
  { name: "Réunion", alpha_2_code: Country.RE },
  { name: "Saint Barthélemy", alpha_2_code: Country.BL },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha_2_code: Country.SH,
  },
  { name: "Saint Kitts and Nevis", alpha_2_code: Country.KN },
  { name: "Saint Lucia", alpha_2_code: Country.LC },
  { name: "Saint Martin (French part)", alpha_2_code: Country.MF },
  { name: "Saint Pierre and Miquelon", alpha_2_code: Country.PM },
  { name: "Saint Vincent and the Grenadines", alpha_2_code: Country.VC },
  { name: "Samoa", alpha_2_code: Country.WS },
  { name: "San Marino", alpha_2_code: Country.SM },
  { name: "Sao Tome and Principe", alpha_2_code: Country.ST },
  { name: "Saudi Arabia", alpha_2_code: Country.SA },
  { name: "Senegal", alpha_2_code: Country.SN },
  { name: "Serbia", alpha_2_code: Country.RS },
  { name: "Seychelles", alpha_2_code: Country.SC },
  { name: "Sierra Leone", alpha_2_code: Country.SL },
  { name: "Singapore", alpha_2_code: Country.SG },
  { name: "Sint Maarten (Dutch part)", alpha_2_code: Country.SX },
  { name: "Slovakia", alpha_2_code: Country.SK },
  { name: "Slovenia", alpha_2_code: Country.SI },
  { name: "Solomon Islands", alpha_2_code: Country.SB },
  { name: "Somalia", alpha_2_code: Country.SO },
  { name: "South Africa", alpha_2_code: Country.ZA },
  {
    name: "South Georgia and the South Sandwich Islands",
    alpha_2_code: Country.GS,
  },
  { name: "South Sudan", alpha_2_code: Country.SS },
  { name: "Spain", alpha_2_code: Country.ES },
  { name: "Sri Lanka", alpha_2_code: Country.LK },
  { name: "Sudan (the)", alpha_2_code: Country.SD },
  { name: "Suriname", alpha_2_code: Country.SR },
  { name: "Svalbard and Jan Mayen", alpha_2_code: Country.SJ },
  { name: "Sweden", alpha_2_code: Country.SE },
  { name: "Switzerland", alpha_2_code: Country.CH },
  { name: "Syrian Arab Republic", alpha_2_code: Country.SY },
  { name: "Taiwan (Province of China)", alpha_2_code: Country.TW },
  { name: "Tajikistan", alpha_2_code: Country.TJ },
  { name: "Tanzania, United Republic of", alpha_2_code: Country.TZ },
  { name: "Thailand", alpha_2_code: Country.TH },
  { name: "Timor-Leste", alpha_2_code: Country.TL },
  { name: "Togo", alpha_2_code: Country.TG },
  { name: "Tokelau", alpha_2_code: Country.TK },
  { name: "Tonga", alpha_2_code: Country.TO },
  { name: "Trinidad and Tobago", alpha_2_code: Country.TT },
  { name: "Tunisia", alpha_2_code: Country.TN },
  { name: "Turkey", alpha_2_code: Country.TR },
  { name: "Turkmenistan", alpha_2_code: Country.TM },
  { name: "Turks and Caicos Islands (the)", alpha_2_code: Country.TC },
  { name: "Tuvalu", alpha_2_code: Country.TV },
  { name: "Uganda", alpha_2_code: Country.UG },
  { name: "Ukraine", alpha_2_code: Country.UA },
  { name: "United Arab Emirates (the)", alpha_2_code: Country.AE },
  {
    name: "United Kingdom of Great Britain and Northern Ireland (the)",
    alpha_2_code: Country.GB,
  },
  {
    name: "United States Minor Outlying Islands (the)",
    alpha_2_code: Country.UM,
  },
  { name: "United States of America (the)", alpha_2_code: Country.US },
  { name: "Uruguay", alpha_2_code: Country.UY },
  { name: "Uzbekistan", alpha_2_code: Country.UZ },
  { name: "Vanuatu", alpha_2_code: Country.VU },
  { name: "Venezuela (Bolivarian Republic of)", alpha_2_code: Country.VE },
  { name: "Viet Nam", alpha_2_code: Country.VN },
  { name: "Virgin Islands (British)", alpha_2_code: Country.VG },
  { name: "Virgin Islands (U.S.)", alpha_2_code: Country.VI },
  { name: "Wallis and Futuna", alpha_2_code: Country.WF },
  { name: "Western Sahara", alpha_2_code: Country.EH },
  { name: "Yemen", alpha_2_code: Country.YE },
  { name: "Zambia", alpha_2_code: Country.ZM },
  { name: "Zimbabwe", alpha_2_code: Country.ZW },
  { name: "Åland Islands", alpha_2_code: Country.AX },
];
