-- DANGER: This script will irrevocably delete all data and schema
-- from the tables listed below.

ALTER TABLE "clerk_user" DROP CONSTRAINT IF EXISTS "clerk_user_person_id_fkey";
ALTER TABLE "person" DROP CONSTRAINT IF EXISTS "person_gender_id_fkey";
ALTER TABLE "person" DROP CONSTRAINT IF EXISTS "person_nationality_id_fkey";
ALTER TABLE "person" DROP CONSTRAINT IF EXISTS "person_document_type_id_fkey";
ALTER TABLE "person" DROP CONSTRAINT IF EXISTS "person_address_id_fkey";
ALTER TABLE "address" DROP CONSTRAINT IF EXISTS "address_country_id_fkey";
ALTER TABLE "person" DROP CONSTRAINT IF EXISTS "person_clerk_id_fkey";

DROP TABLE IF EXISTS "clerk_user";
DROP TABLE IF EXISTS "person";
DROP TABLE IF EXISTS "address";
DROP TABLE IF EXISTS "gender";
DROP TABLE IF EXISTS "document_type";
DROP TABLE IF EXISTS "country";

CREATE TABLE "country" (
                           "id" serial PRIMARY KEY NOT NULL,
                           "alpha_2_code" char(2) NOT NULL,
                           "name" text NOT NULL,
                           CONSTRAINT "country_alpha_2_code_key" UNIQUE("alpha_2_code")
);

CREATE TABLE "address" (
                           "id" serial PRIMARY KEY NOT NULL,
                           "street" text NOT NULL,
                           "number" text,
                           "floor" text,
                           "apartment" text,
                           "city" text NOT NULL,
                           "postal_code" text,
                           "province" text,
                           "country_id" integer,
                           "created_at" timestamp with time zone DEFAULT now(),
                           "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "gender" (
                          "id" serial PRIMARY KEY NOT NULL,
                          "code" text NOT NULL,
                          "name" text NOT NULL,
                          CONSTRAINT "gender_code_key" UNIQUE("code")
);

CREATE TABLE "document_type" (
                                 "id" serial PRIMARY KEY NOT NULL,
                                 "code" text NOT NULL,
                                 "name" text NOT NULL,
                                 CONSTRAINT "document_type_code_key" UNIQUE("code")
);

CREATE TABLE "clerk_user" (
                              "id" serial PRIMARY KEY NOT NULL,
                              "clerk_id" text NOT NULL,
                              "email" text NOT NULL,
                              "image_url" text,
                              "created_at" timestamp with time zone DEFAULT now(),
                              "updated_at" timestamp with time zone DEFAULT now(),
                              CONSTRAINT "clerk_user_clerk_id_key" UNIQUE("clerk_id")
);

CREATE TABLE "person" (
                          "id" serial PRIMARY KEY NOT NULL,
                          "given_name" text NOT NULL,
                          "family_name" text NOT NULL,
                          "full_name" text GENERATED ALWAYS AS (((given_name || ' '::text) || family_name)) STORED,
                          "gender_id" integer,
                          "birth_date" date NOT NULL,
                          "nationality_id" integer,
                          "document_type_id" integer NOT NULL,
                          "document_number" text NOT NULL,
                          "phone_number" text,
                          "address_id" integer,
                          "clerk_id" text UNIQUE,
                          "created_at" timestamp with time zone DEFAULT now(),
                          "updated_at" timestamp with time zone DEFAULT now(),
                          CONSTRAINT "person_document_type_id_document_number_key" UNIQUE("document_type_id","document_number")
);

ALTER TABLE "address" ADD CONSTRAINT "address_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."country"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "person" ADD CONSTRAINT "person_gender_id_fkey" FOREIGN KEY ("gender_id") REFERENCES "public"."gender"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "person" ADD CONSTRAINT "person_nationality_id_fkey" FOREIGN KEY ("nationality_id") REFERENCES "public"."country"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "person" ADD CONSTRAINT "person_document_type_id_fkey" FOREIGN KEY ("document_type_id") REFERENCES "public"."document_type"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "person" ADD CONSTRAINT "person_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."address"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "person" ADD CONSTRAINT "person_clerk_id_fkey" FOREIGN KEY ("clerk_id") REFERENCES "public"."clerk_user"("clerk_id") ON DELETE set null ON UPDATE no action;

-- -----------------------------------------------------------------------------
-- Initial Data Seeding for Lookup Tables
-- -----------------------------------------------------------------------------

INSERT INTO gender (code, name) VALUES
('male', 'Male'),
('female', 'Female'),
('other', 'Other');

INSERT INTO document_type (code, name) VALUES
('dni', 'National Identity Document'),
('passport', 'Passport'),
('other', 'Other');

INSERT INTO country (name, alpha_2_code) VALUES
('Afghanistan','AF'),
('Albania','AL'),
('Algeria','DZ'),
('American Samoa','AS'),
('Andorra','AD'),
('Angola','AO'),
('Anguilla','AI'),
('Antarctica','AQ'),
('Antigua and Barbuda','AG'),
('Argentina','AR'),
('Armenia','AM'),
('Aruba','AW'),
('Australia','AU'),
('Austria','AT'),
('Azerbaijan','AZ'),
('Bahamas (the)','BS'),
('Bahrain','BH'),
('Bangladesh','BD'),
('Barbados','BB'),
('Belarus','BY'),
('Belgium','BE'),
('Belize','BZ'),
('Benin','BJ'),
('Bermuda','BM'),
('Bhutan','BT'),
('Bolivia (Plurinational State of)','BO'),
('Bonaire, Sint Eustatius and Saba','BQ'),
('Bosnia and Herzegovina','BA'),
('Botswana','BW'),
('Bouvet Island','BV'),
('Brazil','BR'),
('British Indian Ocean Territory (the)','IO'),
('Brunei Darussalam','BN'),
('Bulgaria','BG'),
('Burkina Faso','BF'),
('Burundi','BI'),
('Cabo Verde','CV'),
('Cambodia','KH'),
('Cameroon','CM'),
('Canada','CA'),
('Cayman Islands (the)','KY'),
('Central African Republic (the)','CF'),
('Chad','TD'),
('Chile','CL'),
('China','CN'),
('Christmas Island','CX'),
('Cocos (Keeling) Islands (the)','CC'),
('Colombia','CO'),
('Comoros (the)','KM'),
('Congo (the Democratic Republic of the)','CD'),
('Congo (the)','CG'),
('Cook Islands (the)','CK'),
('Costa Rica','CR'),
('Croatia','HR'),
('Cuba','CU'),
('Curaçao','CW'),
('Cyprus','CY'),
('Czechia','CZ'),
('Côte d''Ivoire','CI'),
('Denmark','DK'),
('Djibouti','DJ'),
('Dominica','DM'),
('Dominican Republic (the)','DO'),
('Ecuador','EC'),
('Egypt','EG'),
('El Salvador','SV'),
('Equatorial Guinea','GQ'),
('Eritrea','ER'),
('Estonia','EE'),
('Eswatini','SZ'),
('Ethiopia','ET'),
('Falkland Islands (the) [Malvinas]','FK'),
('Faroe Islands (the)','FO'),
('Fiji','FJ'),
('Finland','FI'),
('France','FR'),
('French Guiana','GF'),
('French Polynesia','PF'),
('French Southern Territories (the)','TF'),
('Gabon','GA'),
('Gambia (the)','GM'),
('Georgia','GE'),
('Germany','DE'),
('Ghana','GH'),
('Gibraltar','GI'),
('Greece','GR'),
('Greenland','GL'),
('Grenada','GD'),
('Guadeloupe','GP'),
('Guam','GU'),
('Guatemala','GT'),
('Guernsey','GG'),
('Guinea','GN'),
('Guinea-Bissau','GW'),
('Guyana','GY'),
('Haiti','HT'),
('Heard Island and McDonald Islands','HM'),
('Holy See (the)','VA'),
('Honduras','HN'),
('Hong Kong','HK'),
('Hungary','HU'),
('Iceland','IS'),
('India','IN'),
('Indonesia','ID'),
('Iran (Islamic Republic of)','IR'),
('Iraq','IQ'),
('Ireland','IE'),
('Isle of Man','IM'),
('Israel','IL'),
('Italy','IT'),
('Jamaica','JM'),
('Japan','JP'),
('Jersey','JE'),
('Jordan','JO'),
('Kazakhstan','KZ'),
('Kenya','KE'),
('Kiribati','KI'),
('Korea (the Democratic People''s Republic of)','KP'),
('Korea (the Republic of)','KR'),
('Kuwait','KW'),
('Kyrgyzstan','KG'),
('Lao People''s Democratic Republic (the)','LA'),
('Latvia','LV'),
('Lebanon','LB'),
('Lesotho','LS'),
('Liberia','LR'),
('Libya','LY'),
('Liechtenstein','LI'),
('Lithuania','LT'),
('Luxembourg','LU'),
('Macao','MO'),
('Madagascar','MG'),
('Malawi','MW'),
('Malaysia','MY'),
('Maldives','MV'),
('Mali','ML'),
('Malta','MT'),
('Marshall Islands (the)','MH'),
('Martinique','MQ'),
('Mauritania','MR'),
('Mauritius','MU'),
('Mayotte','YT'),
('Mexico','MX'),
('Micronesia (Federated States of)','FM'),
('Moldova (the Republic of)','MD'),
('Monaco','MC'),
('Mongolia','MN'),
('Montenegro','ME'),
('Montserrat','MS'),
('Morocco','MA'),
('Mozambique','MZ'),
('Myanmar','MM'),
('Namibia','NA'),
('Nauru','NR'),
('Nepal','NP'),
('Netherlands (the)','NL'),
('New Caledonia','NC'),
('New Zealand','NZ'),
('Nicaragua','NI'),
('Niger (the)','NE'),
('Nigeria','NG'),
('Niue','NU'),
('Norfolk Island','NF'),
('Northern Mariana Islands (the)','MP'),
('Norway','NO'),
('Oman','OM'),
('Pakistan','PK'),
('Palau','PW'),
('Palestine, State of','PS'),
('Panama','PA'),
('Papua New Guinea','PG'),
('Paraguay','PY'),
('Peru','PE'),
('Philippines (the)','PH'),
('Pitcairn','PN'),
('Poland','PL'),
('Portugal','PT'),
('Puerto Rico','PR'),
('Qatar','QA'),
('Republic of North Macedonia','MK'),
('Romania','RO'),
('Russian Federation (the)','RU'),
('Rwanda','RW'),
('Réunion','RE'),
('Saint Barthélemy','BL'),
('Saint Helena, Ascension and Tristan da Cunha','SH'),
('Saint Kitts and Nevis','KN'),
('Saint Lucia','LC'),
('Saint Martin (French part)','MF'),
('Saint Pierre and Miquelon','PM'),
('Saint Vincent and the Grenadines','VC'),
('Samoa','WS'),
('San Marino','SM'),
('Sao Tome and Principe','ST'),
('Saudi Arabia','SA'),
('Senegal','SN'),
('Serbia','RS'),
('Seychelles','SC'),
('Sierra Leone','SL'),
('Singapore','SG'),
('Sint Maarten (Dutch part)','SX'),
('Slovakia','SK'),
('Slovenia','SI'),
('Solomon Islands','SB'),
('Somalia','SO'),
('South Africa','ZA'),
('South Georgia and the South Sandwich Islands','GS'),
('South Sudan','SS'),
('Spain','ES'),
('Sri Lanka','LK'),
('Sudan (the)','SD'),
('Suriname','SR'),
('Svalbard and Jan Mayen','SJ'),
('Sweden','SE'),
('Switzerland','CH'),
('Syrian Arab Republic','SY'),
('Taiwan (Province of China)','TW'),
('Tajikistan','TJ'),
('Tanzania, United Republic of','TZ'),
('Thailand','TH'),
('Timor-Leste','TL'),
('Togo','TG'),
('Tokelau','TK'),
('Tonga','TO'),
('Trinidad and Tobago','TT'),
('Tunisia','TN'),
('Turkey','TR'),
('Turkmenistan','TM'),
('Turks and Caicos Islands (the)','TC'),
('Tuvalu','TV'),
('Uganda','UG'),
('Ukraine','UA'),
('United Arab Emirates (the)','AE'),
('United Kingdom of Great Britain and Northern Ireland (the)','GB'),
('United States Minor Outlying Islands (the)','UM'),
('United States of America (the)','US'),
('Uruguay','UY'),
('Uzbekistan','UZ'),
('Vanuatu','VU'),
('Venezuela (Bolivarian Republic of)','VE'),
('Viet Nam','VN'),
('Virgin Islands (British)','VG'),
('Virgin Islands (U.S.)','VI'),
('Wallis and Futuna','WF'),
('Western Sahara','EH'),
('Yemen','YE'),
('Zambia','ZM'),
('Zimbabwe','ZW'),
('Åland Islands','AX');

SELECT setval('gender_id_seq', (SELECT COALESCE(MAX(id), 1) FROM gender), true);
SELECT setval('country_id_seq', (SELECT COALESCE(MAX(id), 1) FROM country), true);
SELECT setval('document_type_id_seq', (SELECT COALESCE(MAX(id), 1) FROM document_type), true);
SELECT setval('address_id_seq', (SELECT COALESCE(MAX(id), 1) FROM address), true);
SELECT setval('person_id_seq', (SELECT COALESCE(MAX(id), 1) FROM person), true);
SELECT setval('clerk_user_id_seq', (SELECT COALESCE(MAX(id), 1) FROM clerk_user), true);

SELECT 'Database schema and lookup data loaded successfully!' AS status;